# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: setup go sdk
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'

    - name: docker bin hello
      run: docker run hello-world
        
    - name: build a go example bin
      run: |
        pwd
        git clone https://github.com/gin-gonic/examples.git
        cd examples
        go build -o goexample basic/main.go
        cd ..
        mv examples/goexample .
        pwd
        
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: defaultx/actionexample
        
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ccr.ccs.tencentyun.com
        username: ${{ secrets.REGISTRY_NAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
